class Campaign < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................

  # relationships .............................................................
  belongs_to :user

  # validations ...............................................................
  validates :status, presence: true
  validates :name, presence: true
  validates :bid_amount_cents, presence: true
  validates :daily_budget_cents, presence: true
  validates :monthly_budget_cents, presence: true
  validates :redirect_url, presence: true
  validates :total_budget_cents, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............

  # class methods .............................................................
  class << self
  end

  # public instance methods ...................................................

  # protected instance methods ................................................
  protected

  # private instance methods ..................................................
  private
end
