class Click < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................

  # relationships .............................................................
  belongs_to :property
  belongs_to :sponsorship
  belongs_to :developer, class_name: "User", foreign_key: "developer_id"
  belongs_to :sponsor, class_name: "User", foreign_key: "sponsor_id"

  # validations ...............................................................
  validates :developer_id, presence: true
  validates :sponsor_id, presence: true
  validates :sponsorship_id, presence: true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............

  # class methods .............................................................
  class << self
  end

  # public instance methods ...................................................

  # protected instance methods ................................................
  protected

  # private instance methods ..................................................
  private
end
