class User < ApplicationRecord
  # extends ...................................................................

  # includes ..................................................................
  include TagColumns

  # relationships .............................................................
  has_many :developer_impressions, class_name: "Impression", foreign_key: "developer_id"
  has_many :sponsor_impressions, class_name: "Impression", foreign_key: "sponsor_id"
  has_many :developer_clicks, class_name: "Click", foreign_key: "developer_id"
  has_many :sponsor_clicks, class_name: "Click", foreign_key: "sponsor_id"
  has_many :properties
  has_many :campaigns

  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................

  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  tag_columns :roles

  # class methods .............................................................
  class << self
  end

  # public instance methods ...................................................

  # protected instance methods ................................................
  protected

  # private instance methods ..................................................
  private
end
